### ISSUE TITLE
Not Support JasperLake

### ISSUE THREAD

**Issue by ShireCiel** [intel/pcm#387]
Processor Counter Monitor  (2022-03-07 16:06:44 +0100 ID=fd11f3f)

=====  Processor information  =====
Linux arch_perfmon flag  : yes
Hybrid processor         : no
IBRS and IBPB supported  : yes
STIBP supported          : yes
Spec arch caps supported : yes
Max CPUID level          : 27
Error: unsupported processor. Only Intel(R) processors are supported (Atom(R) and microarchitecture codename Nehalem/Nehalem-EP, Atom(tm), Westmere/Clarkdale, Sandy Bridge, Westmere-EP, Sandy Bridge-EP/Jaketown, Nehalem-EX, Westmere-EX, unknown, Centerton, Baytrail, Ivy Bridge, Haswell, Broadwell, Ivy Bridge-EP/EN/EX/Ivytown, Haswell-EP/EN/EX, Cherrytrail, Avoton, Skylake U/Y, Broadwell-EP/EX, Skylake-SP, Cascade Lake-SP, Broadwell-DE, Knights Landing, Apollo Lake, Skylake, Denverton, Icelake-SP, Icelake, Snowridge, Tiger Lake, Kabylake/Whiskey Lake, Alder Lake, Kabylake, Comet Lake, Rocket Lake). CPU model number: 156 Brand: "Intel(R) Celeron(R) N5105 @ 2.00GHz"
Access to Processor Counter Monitor has denied (no MSR or PCI CFG space access).

Please support JasperLake plamform.

**Comment by rdementi** [comment]
accepted as a feature request

**Comment by ShireCiel** [comment]
> accepted as a feature request

Looks ADL have supported.
Any msg new for JasperLake?

**Comment by dmitryluhtionov** [comment]
pcm-power

 Intel(r) Performance Counter Monitor (2022-10-19 10:53:25 +0200 ID=2ae6316f)

 Power Monitoring Utility

=====  Processor information  =====
Hybrid processor         : no
IBRS and IBPB supported  : yes
STIBP supported          : yes
Spec arch caps supported : yes
Max CPUID level          : 24
CPU model number         : 122
Error: unsupported processor. Only Intel(R) processors are supported (Atom(R) and microarchitecture codename Nehalem/Nehalem-EP, Atom(tm), Westmere/Clarkdale, Sandy Bridge, Westmere-EP, Sandy Bridge-EP/Jaketown, Nehalem-EX, Westmere-EX, unknown, Centerton, Baytrail, Ivy Bridge, Haswell, Broadwell, Ivy Bridge-EP/EN/EX/Ivytown, Haswell-EP/EN/EX, Cherrytrail, Avoton, Skylake U/Y, Broadwell-EP/EX, Skylake-SP, Cascade Lake-SP, Broadwell-DE, Knights Landing, Apollo Lake, Skylake, Denverton, Icelake-SP, Icelake, Snowridge, Tiger Lake, Kabylake/Whiskey Lake, Alder Lake, Kabylake, Comet Lake, Rocket Lake, Raptor Lake). CPU model number: 122 Brand: "Intel(R) Pentium(R) Silver N5030 CPU @ 1.10GHz"
Unsupported processor model (122).

Please support Gemini Lake platform

**Comment by NeoChen1024** [comment]
It's 2024, there's still no support for Jasper Lake...

**Comment by rdementi** [comment]
addressed in https://github.com/intel/pcm/pull/836/commits/53aab34d11b5ee26f8c9b231779f58ee93239a7a
