### ISSUE TITLE
Proposed set of changes for Mac Driver

### ISSUE THREAD

**Issue by nealsid** [intel/pcm#446]
During the course of discussion it's come up to separate TopologyEntry into a different header file so it can be included by both kernel and user code.  When I did that, I ran into a few dependencies.  There is a C wrapper around IOKit in [PcmMsr/MacMsr/DriverInterface.{c,h}](https://github.com/intel/pcm/blob/master/src/MacMSRDriver/DriverInterface.c), which means TopologyEntry cannot be in a namespace if it is used there, but TopologyEntry depends on typedefs inside the pcm namespace in [types.h](https://github.com/intel/pcm/blob/master/src/types.h).  DriverInterface does not seem to be necessary anymore, as it is a very thin wrapper that just forwards calls to IOKit, so this is what I would like to propose to do:

- Update DriverInterface to fix some type inconsistencies (e.g. interspersed uses of int32/uint32/uint64, and passing size as count rather than a number of bytes in the numInstance methods)
- Merge DriverInterface into MSRAccessor.cpp
- move TopologyEntry into it's own header file
- Hopefully write some automated test infrastructure for the driver as this happens

I will have to split it up over several changes just to make sure I don't break anything, as I'm new to both IOKit and kexts.

**Comment by rdementi** [comment]
this looks good to me. Looking forward to see the patches
