### ISSUE TITLE
Install paths

### ISSUE THREAD

**Issue by nealsid** [intel/pcm#449]
In the root CMakeLists.txt, there is a section determining the install path:
```
if(CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT OR ${CMAKE_INSTALL_PREFIX} STREQUAL "/usr")  # default is "/usr/local", pcm default is "/usr"
  set(CMAKE_INSTALL_PREFIX "/usr" CACHE PATH "..." FORCE)
else()
  set(CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}/usr" CACHE PATH "..." FORCE)
endif()
```

Is there any particular reason it is forced into the cache in the if statement? And, the else cause seems to cause problems because the default is /usr/local (as comment indicates), but then the path ends up being "/usr/local/usr" which is not typical.  I can remove or update this section if I'm not mistaken about this.

**Comment by markovamaria** [comment]
Hi @nealsid, 
this cache line appeared to fix issue - https://github.com/intel-innersource/applications.analyzers.pcm/issues/169. 
Could you please describe particular test case (run lines) where you faced with issue?

**Comment by markovamaria** [comment]
>> I do not appear to have access to that issue. 
There were issue with appending of /usr to install part in queue of cmake runs:
```
$ mkdir build && cd build
$ cmake ..
...
-- Install directory: /usr
...
$ cmake ..
...
-- Install directory: /usr/usr
...
$ cmake ..
...
-- Install directory: /usr/usr/usr
...
```
I believe, this section is required.

>> then the path ends up being "/usr/local/usr" which is not typical.
I'll look into it.

**Comment by markovamaria** [comment]
Merged PR with removing of legacy behavior related to CMAKE_INSTALL_PREFIX -  https://github.com/intel/pcm/pull/457.

**Comment by rdementi** [comment]
resolved
