### ISSUE TITLE
FreeBSD pcm build failed "unable to find library -lPCM_STATIC"

### ISSUE THREAD

**Issue by Alexander-Alexeev** [intel/pcm#477]
```
# ls
pcm
# cd pcm
# mkdir build
# cd build
# cmake ..
-- The C compiler identification is Clang 6.0.1
-- The CXX compiler identification is Clang 6.0.1
System is unknown to cmake, create:
Platform/Isilon OneFS to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
-- Check for working C compiler: /usr/bin/cc
System is unknown to cmake, create:
Platform/Isilon OneFS to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
System is unknown to cmake, create:
Platform/Isilon OneFS to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/CC
System is unknown to cmake, create:
Platform/Isilon OneFS to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
-- Check for working CXX compiler: /usr/bin/CC -- works
-- Detecting CXX compiler ABI info
System is unknown to cmake, create:
Platform/Isilon OneFS to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
System is unknown to cmake, create:
Platform/Isilon OneFS to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
System is unknown to cmake, create:
Platform/Isilon OneFS to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
System is unknown to cmake, create:
Platform/Isilon OneFS to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
-- Detecting CXX compile features - done
-- Looking for pthread.h
System is unknown to cmake, create:
Platform/Isilon OneFS to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
-- Looking for pthread.h - found
-- Looking for pthread_create
System is unknown to cmake, create:
Platform/Isilon OneFS to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
System is unknown to cmake, create:
Platform/Isilon OneFS to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE
-- System: Isilon OneFS-9.5.0.0
-- Local SIMDJSON exists: /root/pcm2022_2/pcm/src/simdjson/singleheader/simdjson.h
-- Install directory: /usr/local
-- Configuring done
-- Generating done
-- Build files have been written to: /root/pcm2022_2/pcm/build
# cmake --build .
Scanning dependencies of target pcm-raw
[  3%] Building CXX object src/CMakeFiles/pcm-raw.dir/pcm-raw.cpp.obj
[  6%] Building CXX object src/CMakeFiles/pcm-raw.dir/simdjson/singleheader/simdjson.cpp.obj
[  9%] Linking CXX executable ../bin/pcm-raw
/usr/bin/ld: error: unable to find library -lPCM_STATIC
c++: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[2]: *** [bin/pcm-raw] Error 1
gmake[1]: *** [src/CMakeFiles/pcm-raw.dir/all] Error 2
gmake: *** [all] Error 2
```

**Comment by opcm** [comment]
could you try a more recent clang version (more recent than your 6.0.1) on the latest PCM version in the master branch? Our FreeBSD build with clang 13 is successful: https://github.com/intel/pcm/actions/runs/3592039863/jobs/6047291133

**Comment by ogbrugge** [comment]
Not sure why but it could be that -lPCM_STATIC is not properly replaced here? As far as I know the library name is not in capitals.
@Alexander-Alexeev, can you run the cmake with the -v option like indicated in the error message? I would like to see the exact command that is being executed.

**Comment by Alexander-Alexeev** [comment]
@markovamaria 12.0-RELEASE but it is highly modified and run on appliance

**Comment by markovamaria** [comment]
Hi @Alexander-Alexeev, 
I think issue is in system definition. You system is defined as "-- System: Isilon OneFS-9.5.0.0". 
Current CMake file has support UNIX and MSVC. If you expect see UNIX behavior, I'd suggest you try to re-define this variable directly to FreeBSD, for example.

**Comment by Alexander-Alexeev** [comment]
Tried ... I will continue debugging later but for now 

```
# cmake -DCMAKE_SYSTEM_NAME="FreeBSD" ..
-- The C compiler identification is Clang 6.0.1
-- The CXX compiler identification is Clang 6.0.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/CC
-- Check for working CXX compiler: /usr/bin/CC -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
CMake Error: TRY_RUN() invoked in cross-compiling mode, please set the following cache variables appropriately:
   THREADS_PTHREAD_ARG (advanced)
For details see /root/pcm_v1/pcm/build/TryRunResults.cmake
-- Check if compiler accepts -pthread - no
-- Found Threads: TRUE
-- System: FreeBSD
-- Build type: Release
-- initial CMAKE_CXX_FLAGS:
-- initial CMAKE_C_FLAGS:
-- CMAKE_CXX_FLAGS:  -Wno-unknown-pragmas -fPIC
-- CMAKE_C_FLAGS:  -Wno-unknown-pragmas -fPIC
-- Local SIMDJSON exists: /root/pcm_v1/pcm/src/simdjson/singleheader/simdjson.h
-- Install directory: /usr/local
-- CPACK_GENERATOR is TXZ
-- Configuring incomplete, errors occurred!
See also "/root/pcm_v1/pcm/build/CMakeFiles/CMakeOutput.log".
See also "/root/pcm_v1/pcm/build/CMakeFiles/CMakeError.log".

```

and 

```
# cat /root/pcm_v1/pcm/build/CMakeFiles/CMakeError.log
Determining if the pthread_create exist failed with the following output:
Change Dir: /root/pcm_v1/pcm/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/local/bin/gmake" "cmTC_49fcf/fast"
/usr/local/bin/gmake -f CMakeFiles/cmTC_49fcf.dir/build.make CMakeFiles/cmTC_49fcf.dir/build
gmake[1]: Entering directory `/root/pcm_v1/pcm/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_49fcf.dir/CheckSymbolExists.c.o
/usr/bin/cc     -o CMakeFiles/cmTC_49fcf.dir/CheckSymbolExists.c.o   -c /root/pcm_v1/pcm/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_49fcf
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_49fcf.dir/link.txt --verbose=1
/usr/bin/cc       CMakeFiles/cmTC_49fcf.dir/CheckSymbolExists.c.o  -o cmTC_49fcf
/usr/bin/ld: error: undefined symbol: pthread_create
>>> referenced by CheckSymbolExists.c
>>>               CMakeFiles/cmTC_49fcf.dir/CheckSymbolExists.c.o:(main)
cc: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[1]: *** [cmTC_49fcf] Error 1
gmake[1]: Leaving directory `/root/pcm_v1/pcm/build/CMakeFiles/CMakeTmp'
gmake: *** [cmTC_49fcf/fast] Error 2

File /root/pcm_v1/pcm/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if compiler accepts -pthread returned PLEASE_FILL_OUT-FAILED_TO_RUN instead of 2. The compiler had the following output:
Change Dir: /root/pcm_v1/pcm/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/local/bin/gmake" "cmTC_bd3df/fast"
/usr/local/bin/gmake -f CMakeFiles/cmTC_bd3df.dir/build.make CMakeFiles/cmTC_bd3df.dir/build
gmake[1]: Entering directory `/root/pcm_v1/pcm/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_bd3df.dir/CheckForPthreads.c.o
/usr/bin/cc     -o CMakeFiles/cmTC_bd3df.dir/CheckForPthreads.c.o   -c /usr/local/share/cmake/Modules/CheckForPthreads.c
Linking C executable cmTC_bd3df
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_bd3df.dir/link.txt --verbose=1
/usr/bin/cc       CMakeFiles/cmTC_bd3df.dir/CheckForPthreads.c.o  -o cmTC_bd3df -pthread
gmake[1]: Leaving directory `/root/pcm_v1/pcm/build/CMakeFiles/CMakeTmp'

```

**Comment by Alexander-Alexeev** [comment]
@markovamaria Do you have any recommendations?

**Comment by markovamaria** [comment]
> cmake -DCMAKE_SYSTEM_NAME="FreeBSD" ..

Please verify, that you have pthreads installed on you host

**Comment by markovamaria** [comment]
> @markovamaria Do you have any recommendations?

Please verify, that you have pthreads installed on your host.

And by the way, which version of CMake do you use?

**Comment by Alexander-Alexeev** [comment]
# cmake -version
cmake version 3.7.2

**Comment by Alexander-Alexeev** [comment]
```
# cat a.c
#include<pthread.h>
#include<stdio.h>
// a simple pthread example
// compile with -lpthreads

// create the function to be executed as a thread
void *thread(void *ptr)
{
    int type = (int) ptr;
    fprintf(stderr,"Thread - %d\n",type);
    return  ptr;
}

int main(int argc, char **argv)
{
    // create the thread objs
    pthread_t thread1, thread2;
    int thr = 1;
    int thr2 = 2;
    // start the threads
    pthread_create(&thread1, NULL, *thread, (void *) thr);
    pthread_create(&thread2, NULL, *thread, (void *) thr2);
    // wait for threads to finish
    pthread_join(thread1,NULL);
    pthread_join(thread2,NULL);
    return 0;
}#                                                                                                                                                                                                                                                                # clang -o pthread_test -l pthread a.c
a.c:21:45: warning: cast to 'void *' from smaller integer type 'int' [-Wint-to-void-pointer-cast]
    pthread_create(&thread1, NULL, *thread, (void *) thr);
                                            ^
a.c:22:45: warning: cast to 'void *' from smaller integer type 'int' [-Wint-to-void-pointer-cast]
    pthread_create(&thread2, NULL, *thread, (void *) thr2);
                                            ^
2 warnings generated.
# ./pthread_test
Thread - 2
Thread - 1



```

**Comment by Alexander-Alexeev** [comment]
lib `pthread` is fine

**Comment by markovamaria** [comment]
> -- The C compiler identification is Clang 8.0.1
> -- The CXX compiler identification is Clang 8.0.1
> System is unknown to cmake, create:
> Platform/Isilon OneFS to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
> -- Check for working C compiler: /usr/bin/cc
> System is unknown to cmake, create:
> Platform/Isilon OneFS to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> System is unknown to cmake, create:
> Platform/Isilon OneFS to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/CC
> System is unknown to cmake, create:
> Platform/Isilon OneFS to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
> -- Check for working CXX compiler: /usr/bin/CC -- works
> -- Detecting CXX compiler ABI info
> System is unknown to cmake, create:
> Platform/Isilon OneFS to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> System is unknown to cmake, create:
> Platform/Isilon OneFS to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
> System is unknown to cmake, create:
> Platform/Isilon OneFS to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
> System is unknown to cmake, create:
> Platform/Isilon OneFS to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
> -- Detecting CXX compile features - done
> -- Looking for pthread.h
> System is unknown to cmake, create:
> Platform/Isilon OneFS to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
> -- Looking for pthread.h - found
> -- Looking for pthread_create
> System is unknown to cmake, create:
> Platform/Isilon OneFS to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
> -- Looking for pthread_create - not found
> -- Check if compiler accepts -pthread
> System is unknown to cmake, create:
> Platform/Isilon OneFS to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
> -- Check if compiler accepts -pthread - yes
> -- Found Threads: TRUE
> -- System: Isilon OneFS-9.5.0.0
> -- Local SIMDJSON exists: /root/pcm/src/simdjson/singleheader/simdjson.h
> -- Install directory: /usr/local
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /root/pcm/build

Let's summarize, do you still have this cmake build fail when you use system configuration as in your 1st comment? 
- "Platform/Isilon OneFS" + Clang 6.0.1  + cmake 3.2 ?

I'd suggest to follow approach or cross-platform building with FreeBSD, so let's try to resolve Cmake issue. 

I compared your 1st (build error) and 2nd (cmake error) logs and see the difference in pthread response:
- -- Check if compiler accepts -pthread - no   with Clang 6.1.0
vs.
- -- Check if compiler accepts -pthread - yes     with Clang 8.1.0

Could you please try to run cmake with the newest possible Clang compiler, FreeBSD and share log again? 
If FreeBSD will fail, please try Linux also.

Another issue which I see in cross-compilation logs: 
CMake Error: TRY_RUN() invoked in cross-compiling mode, please set the following cache variables appropriately:
   THREADS_PTHREAD_ARG (advanced)
For details see /root/pcm_v1/pcm/build/TryRunResults.cmake 

In some internet solutions it is suggested to setup THREADS_PTHREAD_ARG must be set to "2". You can try this also.

**Comment by markovamaria** [comment]
> ```
> 
> # cmake --build .
> [  3%] Linking CXX executable ../bin/pcm-raw
> ld: error: unable to find library -lPCM_STATIC
> c++: error: linker command failed with exit code 1 (use -v to see invocation)
> gmake[2]: *** [bin/pcm-raw] Error 1
> gmake[1]: *** [src/CMakeFiles/pcm-raw.dir/all] Error 2
> gmake: *** [all] Error 2
> ```

Let's summarize, do you still have this cmake build fail when you use system configuration as in your 1st comment:

"Platform/Isilon OneFS" + Clang 6.0.1 + cmake 3.7.2 ?
I'd suggest to follow approach or cross-platform building with FreeBSD, so let's try to resolve Cmake issue.

I compared your 1st (build error) and 2nd (cmake error) logs and see the difference in pthread response:

-- Check if compiler accepts -pthread - no with Clang 6.1.0
vs.
-- Check if compiler accepts -pthread - yes with Clang 8.1.0
Could you please try to run cmake with the newest possible Clang compiler, FreeBSD and share log again?
If FreeBSD will fail, please try Linux also.

Another issue which I see in cross-compilation logs:
CMake Error: TRY_RUN() invoked in cross-compiling mode, please set the following cache variables appropriately:
THREADS_PTHREAD_ARG (advanced)
For details see /root/pcm_v1/pcm/build/TryRunResults.cmake

In some internet solutions it is suggested to redefine var "THREADS_PTHREAD_ARG must be set to "2" ". You can try this also.

**Comment by Alexander-Alexeev** [comment]
> which clang do you used for compilation of pthread-check app?

# clang --version
FreeBSD clang version 8.0.1 (tags/RELEASE_801/final 366581) (based on LLVM 8.0.1)
Target: x86_64-unknown-freebsd13.0
Thread model: posix
InstalledDir: /usr/bin

**Comment by Alexander-Alexeev** [comment]
So this is last try 

```
aalexee-2j7qut7-1# cmake ..
-- The C compiler identification is Clang 8.0.1
-- The CXX compiler identification is Clang 8.0.1
System is unknown to cmake, create:
Platform/Isilon OneFS to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
-- Check for working C compiler: /usr/bin/cc
System is unknown to cmake, create:
Platform/Isilon OneFS to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
System is unknown to cmake, create:
Platform/Isilon OneFS to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/CC
System is unknown to cmake, create:
Platform/Isilon OneFS to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
-- Check for working CXX compiler: /usr/bin/CC -- works
-- Detecting CXX compiler ABI info
System is unknown to cmake, create:
Platform/Isilon OneFS to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
System is unknown to cmake, create:
Platform/Isilon OneFS to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
System is unknown to cmake, create:
Platform/Isilon OneFS to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
System is unknown to cmake, create:
Platform/Isilon OneFS to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
-- Detecting CXX compile features - done
-- Looking for pthread.h
System is unknown to cmake, create:
Platform/Isilon OneFS to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
-- Looking for pthread.h - found
-- Looking for pthread_create
System is unknown to cmake, create:
Platform/Isilon OneFS to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
System is unknown to cmake, create:
Platform/Isilon OneFS to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE
-- System: Isilon OneFS-9.5.0.0
-- Local SIMDJSON exists: /root/pcm/src/simdjson/singleheader/simdjson.h
-- Install directory: /usr/local
-- Configuring done
-- Generating done
-- Build files have been written to: /root/pcm/build


aalexee-2j7qut7-1# cmake --build .
Scanning dependencies of target pcm-raw
[  3%] Building CXX object src/CMakeFiles/pcm-raw.dir/pcm-raw.cpp.obj
[  6%] Building CXX object src/CMakeFiles/pcm-raw.dir/simdjson/singleheader/simdjson.cpp.obj
[  9%] Linking CXX executable ../bin/pcm-raw
ld: error: unable to find library -lPCM_STATIC
c++: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[2]: *** [bin/pcm-raw] Error 1
gmake[1]: *** [src/CMakeFiles/pcm-raw.dir/all] Error 2
gmake: *** [all] Error 2

aalexee-2j7qut7-1# cmake -version
cmake version 3.7.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
aalexee-2j7qut7-1# clang --version
FreeBSD clang version 8.0.1 (tags/RELEASE_801/final 366581) (based on LLVM 8.0.1)
Target: x86_64-unknown-freebsd13.0
Thread model: posix
InstalledDir: /usr/bin

```

**Comment by Alexander-Alexeev** [comment]
As you can see same issue with clang 8.0.1

**Comment by Alexander-Alexeev** [comment]
I see no such file "TryRunResults.cmake"
and could clarify where can I change value for "THREADS_PTHREAD_ARG" ?

**Comment by markovamaria** [comment]
> So this is last try
> 
> ```
> aalexee-2j7qut7-1# cmake ..
> -- The C compiler identification is Clang 8.0.1
> -- The CXX compiler identification is Clang 8.0.1
> System is unknown to cmake, create:
> Platform/Isilon OneFS to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
> -- Check for working C compiler: /usr/bin/cc
> System is unknown to cmake, create:
> Platform/Isilon OneFS to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
...

> As you can see same issue with clang 8.0.1
Not exactly.

I'd suggest to follow approach or cross-platform building with FreeBSD and try to resolve Cmake issue.
Could you please run ` cmake -DCMAKE_SYSTEM_NAME="FreeBSD" ..  ` instead of `cmake ... ` ?  Clang 8.1.0 is fine.

**Comment by rdementi** [comment]
it seems we can't support "Platform/Isilon OneFS"
