### ISSUE TITLE
Memory Read and Write return zero even secure boot is disabled

### ISSUE THREAD

**Issue by dino945** [intel/pcm#489]
Hi, 

I currently running PCM inside AlderLake platform.
I have disable secure boot from bios and able to run pcm command.
However, zero is returned for both memory read and write.
![image](https://user-images.githubusercontent.com/103552280/210472550-7c6dcf32-3278-4023-abf3-0a76e17cebf9.png)

There is a message regarding linux perf event.
![image](https://user-images.githubusercontent.com/103552280/210472597-da01205a-22ad-4eb6-b465-6a6d8c4a73d9.png)

Anyone have clues on this? 
Thanks^^

**Comment by rdementi** [comment]
thanks for reporting this issue. Could you please provide the full output of pcm?

**Comment by dino945** [comment]
Hi @rdementi , here is the full output
[PCM.log](https://github.com/intel/pcm/files/10351494/PCM.log)

**Comment by rdementi** [comment]
thanks. Could you please run this command "pcm -i=10 -csv=pcm.csv" and share the output.pcm.csv file? It will run for 10 seconds.

**Comment by dino945** [comment]
Hi @rdementi , 
[pcm.csv](https://github.com/intel/pcm/files/10356625/pcm.csv)
![image](https://user-images.githubusercontent.com/103552280/210909580-d94a5160-9f55-402c-8e2f-6d6789c4db56.png)
READ and WRITE for full 10s is displayed as 0.

**Comment by rdementi** [comment]
Thanks for the collection. We could not reproduce it on our Alder Lake system. Could you please contact roman.dementiev@intel.com to check how to debug it further?
