### ISSUE TITLE
Gemini Lake is unsupported?

### ISSUE THREAD

**Issue by jorgp2** [intel/pcm#498]
I stumbled upon this project today and tried to run it on my N4100 based laptop, but was greeted with an unsupported processor error:

`Error: unsupported processor. Only Intel(R) processors are supported (Atom(R) and microarchitecture codename Nehalem/Nehalem-EP, Atom(tm), Westmere/Clarkdale, Sandy Bridge, Westmere-EP, Sandy Bridge-EP/Jaketown, Nehalem-EX, Westmere-EX, unknown, Centerton, Baytrail, Ivy Bridge, Haswell, Broadwell, Ivy Bridge-EP/EN/EX/Ivytown, Haswell-EP/EN/EX, Cherrytrail, Avoton, Skylake U/Y, Broadwell-EP/EX, Skylake-SP, Cascade Lake-SP, Broadwell-DE, Knights Landing, Apollo Lake, Skylake, Denverton, Icelake-SP, Icelake, Snowridge, Tiger Lake, Kabylake/Whiskey Lake, Alder Lake, Kabylake, Comet Lake, Rocket Lake). CPU model number: 122 Brand: "Intel(R) Celeron(R) N4100 CPU @ 1.10GHz"`

It seems like an oversight to me for Apollo Lake to be supported but not Gemini lake, as Gemini Lake should support a super set of Apollo Lake's features.

**Comment by rdementi** [comment]
thanks for the report. We will consider your request

**Comment by rdementi** [comment]
this should be resolved now
