### ISSUE TITLE
`./pcm-pcie 0.5 -csv=test.log` runs >100x faster | integers go half speed

### ISSUE THREAD

**Issue by malventano** [intel/pcm#509]
Running `pcm-pcie` with delays below 1-second returns hundreds of entries per second.
```
# time ./pcm-pcie 0.5 -csv=test.log -i=1000
...
real    0m3.010s
user    0m0.275s
sys     0m2.596s
```
1000 x 0.5 != 3

`pcm-core`, `pcm-iio`, `pcm-latency`, `pcm-memory`, `pcm-numa`, and `pcm-power` all appear to function properly.

**Comment by malventano** [comment]
Additionally, whole numbers appear to be doubled:
```
# time ./pcm/build/bin/pcm-pcie 1 -csv=test.log -i=10
...
real    0m20.489s
user    0m0.293s 
sys     0m0.423s 

# time ./pcm/build/bin/pcm-pcie 2 -csv=test.log -i=10
...
real    0m40.480s
user    0m0.290s 
sys     0m0.563s 
```

**Comment by antonovalexnn** [comment]
Hello @malventano,

Thank you for reporting this issue. The fix will be available in next update

**Comment by rdementi** [comment]
the fix has been merged into the master branch
