### ISSUE TITLE
What are the release plans for CXL Type-3 Device Bandwidth measurement?

### ISSUE THREAD

**Issue by shkimmm** [intel/pcm#548]
Hello,

I want to measure the bandwidth of CXL Type-3 Device. 
Currently, CXL Type-3 devices are recognized and used as new Numa nodes. It is recognized as System-ram of the new node.

When will the bandwidth measurement method of CXL-Type3 Memory provided by Sapphire rappids be released?

**Comment by rdementi** [comment]
let me check. I will get back when I will have more information.

**Comment by rdementi** [comment]
this feature has been added in the master branch https://github.com/intel/pcm/blob/master/doc/CXL_README.md

**Comment by shkimmm** [comment]
Thanks :)
