### ISSUE TITLE
Can pcm tool run under Windows 11?

### ISSUE THREAD

**Issue by qguo29** [intel/pcm#549]
Trying to build "msr.sys" in VS 2022, with Windows 11 version 22H2 SDK and WDK, got the following errors:

1>------ Build started: Project: MSR, Configuration: Debug|x64 ------
1>  Building 'MSR' with toolset 'WindowsKernelModeDriver10.0' and the 'Universal' target platform.
1>  msrmain.c
1>...\pcm\src\WinMSRDriver\msrmain.c(259,24): error C2220: the following warning is treated as an error
1>...\pcm\src\WinMSRDriver\msrmain.c(259,24): warning C4996: 'HalSetBusDataByOffset': was declared deprecated
1>...\pcm\src\WinMSRDriver\msrmain.c(277,24): warning C4996: 'HalGetBusDataByOffset': was declared deprecated
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
Build failed.

**Comment by opcm** [comment]
I think you can resolve this by disabling the warning or disabling treating warnings as errors.

**Comment by rdementi** [comment]
this should be resolved now. If not, please reopen
