### ISSUE TITLE
pcm-iio reports wrong IB write/read data on iio pcie stack 

### ISSUE THREAD

**Issue by fmiao2372** [intel/pcm#559]
pcm-iio fails to dump stack "IIO Stack 2 - PCIe0" to get Intel data center max GPU(device id: 0BDB) pcie r/w,  it always zero.
However, the "IIO Stack 1 - DMI" show the corrected data, about 40G. 

my cpu model:
model           : 143
model name      : Intel(R) Xeon(R) Gold 6438Y+

results of pcm-iio:
![image](https://github.com/intel/pcm/assets/90737993/a60ac6d6-c3bc-4288-9870-c003199f5127)

And, it works on Intel(R) Xeon(R) Platinum 8469 CPU @2.00GHz.

Does pcm-iio support all types of SPR? Is there any other iio stack mapping of SPR CPU?
pcm-iio.cpp line 173
![image](https://github.com/intel/pcm/assets/90737993/2d645153-9465-470f-9145-83db3096d807)

**Comment by rdementi** [comment]
this has been fixed some time ago
