### ISSUE TITLE
Artifacts are expired....

### ISSUE THREAD

**Issue by sopgenorth** [intel/pcm#580]
It seems that a free variant of AppVeyor (come on intel...) is being used that only keeps artifacts around for 1 month: https://ci.appveyor.com/project/opcm/pcm/build/job/xhyf523nrxtbe5om/artifacts

Perhaps these build artifacts could be stashed on the Github releases for accessibility?

**Comment by opcm** [comment]
Thank you for letting us know. The artifacts have been re-generated. We will consider your suggestion.
