### ISSUE TITLE
ERROR: MDF PMU not found

### ISSUE THREAD

**Issue by shashankshashank44** [intel/pcm#587]
I'm using pcm-memory and tried to attach an application to measure memory activity. As I run pcm-memory with a program on top, I was faced with the above error message `ERROR: MDF PMU not found` and got `Failed to start program` message. Processor is Sapphire rapids based Xeon gold. I realized that all pcm tools (like pcm-power, pcm-raw) have the above mentioned error. Any idea of what might be the issue?

**Comment by opcm** [comment]
could you please post the complete output of one of the tools?

**Comment by shashankshashank44** [comment]
Thanks for the response, Issue was related to file system and has been solved.
