### ISSUE TITLE
Is pcm supported for Core i7? 

### ISSUE THREAD

**Issue by vimalk78** [intel/pcm#591]
Is pcm supported for Core i7?  or is it supported for Core processors in general? or does it support only Xeon?

I am using `pcm-power` on my laptop with below processor

```
$ lscpu 
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         39 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  16
  On-line CPU(s) list:   0-15
Vendor ID:               GenuineIntel
  Model name:            11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
    CPU family:          6
    Model:               141
    Thread(s) per core:  2
    Core(s) per socket:  8
    Socket(s):           1
    Stepping:            1
    CPU(s) scaling MHz:  30%
    CPU max MHz:         4800.0000
    CPU min MHz:         800.0000
```

i am getting following error
```
Unsupported processor model (140).
```

**Comment by vimalk78** [comment]
perhaps same as https://github.com/intel/pcm/issues/298 ?

**Comment by rdementi** [comment]
the main pcm utility should be supported on your CPU. For pcm-power this is the answer: https://github.com/intel/pcm/blob/master/doc/FAQ.md#q5

**Comment by vimalk78** [comment]
actually i have been using `pcm-senseor-server` and connecting the prometheus + grafana to it to view the metrics. But that grafana doesn't show Socket Energy Consumption. It shows 'No Data' message.

i compiled the `pcm-sensor-server` locally and using that.

**Comment by rdementi** [comment]
does the pcm command line utility show the energy consumption? Could you post a screenshot from the pcm output?

**Comment by vimalk78** [comment]
it seems to show power values

```
$ sudo pcm

 Intel(r) Performance Counter Monitor (2023-07-14 10:01:29 +0200 ID=ccc53261)



=====  Processor information  =====
Linux arch_perfmon flag  : yes
Hybrid processor         : no
IBRS and IBPB supported  : yes
STIBP supported          : yes
Spec arch caps supported : yes
Max CPUID level          : 27
CPU model number         : 141
Number of physical cores: 8
Number of logical cores: 16
Number of online logical cores: 16
Threads (logical cores) per physical core: 2
Num sockets: 1
Physical cores per socket: 8
Last level cache slices per socket: 8
Core PMU (perfmon) version: 5
Number of core PMU generic (programmable) counters: 8
Width of generic (programmable) counters: 48 bits
Number of core PMU fixed counters: 4
Width of fixed counters: 48 bits
Nominal core frequency: 2500000000 Hz
IBRS enabled in the kernel   : yes
STIBP enabled in the kernel  : no
The processor is not susceptible to Rogue Data Cache Load: yes
The processor supports enhanced IBRS                     : yes
Package thermal spec power: 45 Watt; Package minimum power: 0 Watt; Package maximum power: 0 Watt;

INFO: Linux perf interface to program uncore PMUs is NOT present

 Closed perf event handles
Trying to use Linux perf events...
Successfully programmed on-core PMU using Linux perf

Detected 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz "Intel(r) microarchitecture codename Tiger Lake" stepping 1 microcode level 0x46

 EXEC  : instructions per nominal CPU cycle
 IPC   : instructions per CPU cycle
 FREQ  : relation to nominal CPU frequency='unhalted clock ticks'/'invariant timer ticks' (includes Intel Turbo Boost)
 AFREQ : relation to nominal CPU frequency while in active state (not in power-saving C state)='unhalted clock ticks'/'invariant timer ticks while in C0-state'  (includes Intel Turbo Boost)
 L3MISS: L3 (read) cache misses 
 L2MISS: L2 (read) cache misses (including other core's L2 cache *hits*) 
 L3HIT : L3 (read) cache hit ratio (0.00-1.00)
 L2HIT : L2 cache hit ratio (0.00-1.00)
 L3MPI : number of L3 (read) cache misses per instruction
 L2MPI : number of L2 (read) cache misses per instruction
 READ  : bytes read from main memory controller (in GBytes)
 WRITE : bytes written to main memory controller (in GBytes)
 TEMP  : Temperature reading in 1 degree Celsius relative to the TjMax temperature (thermal headroom): 0 corresponds to the max temperature
 energy: Energy in Joules


 Core (SKT) | EXEC | IPC  | FREQ  | AFREQ | L3MISS | L2MISS | L3HIT | L2HIT | L3MPI | L2MPI |  TEMP

```

**Comment by vimalk78** [comment]
> could you post the full output? The data values are cut off

updated comment

**Comment by rdementi** [comment]
> actually i have been using `pcm-senseor-server` and connecting the prometheus + grafana to it to view the metrics. But that grafana doesn't show Socket Energy Consumption. It shows 'No Data' message.
> 
> i compiled the `pcm-sensor-server` locally and using that.

do other metrics show up and just "Socket Energy Consumption" is missing?

**Comment by vimalk78** [comment]
> do other metrics show up and just "Socket Energy Consumption" is missing?

the charts which are zero are: 
- all Memory Bandwidth related charts
- QPI Data traffic related charts
- Socket0 Energy Consumption

![image](https://github.com/intel/pcm/assets/3284044/e885243f-b1c0-4acf-b63d-a04268da8e5a)

![image](https://github.com/intel/pcm/assets/3284044/6f3fb74c-5e28-4b37-bc23-23556c3d2506)

![image](https://github.com/intel/pcm/assets/3284044/8b321b39-0be4-4ccd-ade2-693292c4e9bb)

![image](https://github.com/intel/pcm/assets/3284044/410e59aa-adcf-4794-8719-080873562934)

![image](https://github.com/intel/pcm/assets/3284044/5e3508d3-8dfb-4e93-a8d2-d8bf92052d29)

**Comment by vimalk78** [comment]
```
pcm-power reports "Unsupported processor model". Can you add support for pcm-power for my CPU?

Answer: most likely you have a client CPU which does not have required hardware performance monitoring units. PCM-power can not work without them.
```

if `pcm` can report power, it means CPU has what is needed to read power. (perhaps RAPL). then `pcm-sensor-server` also should be able to read power. .right?

**Comment by opcm** [comment]
correct. Thank you for reporting the issue.

**Comment by vimalk78** [comment]
is there something i can contribute to fix the issue (if it is a minor issue) ?
