### ISSUE TITLE
MacMSRDriver seems to left the system very insecure?

### ISSUE THREAD

**Issue by trulyspinach** [intel/pcm#595]
Hi,

It seems that in the current version having the MacMSRDriver kext loaded will keep the kernel interface open for any user program? Which IMO is very insecure as any program can then use the driver to gain R/W access to MSR and etc.

Please forgive me if I missed anything, otherwise was this by design? Maybe we should make the `pcm` userspace program load and unload the kext once it's done with it? Or limit the access to root user by checking with `clientHasPrivilege` in the user client?

**Comment by opcm** [comment]
that is a good suggestion. Would it be possible for you to create a pull request with the proposed changes? Your contribution is very much appreciated.

**Comment by trulyspinach** [comment]
@opcm thanks for the swift response. I’ll open a pull request.

**Comment by opcm** [comment]
@trulyspinach that is awesome! looking forward
