### ISSUE TITLE
pcm-pcie or pcm-iio does not support Emerald Rapid-SP processor

### ISSUE THREAD

**Issue by azril-ahmad** [intel/pcm#605]
Noticed once running pcm-pcie or pcm-iio under Emerald Rapid-SP (EMR-SP) will return "Error of unsupported processor".
FYI, the verification is using the latest/greatest code from master branch.

**Below is the sample of error snapshot:**
![image](https://github.com/intel/pcm/assets/90176387/4b3d9855-22aa-4a58-9efc-f7625a99e419)

**Comment by ogbrugge-work** [comment]
Hi,

as usual with unreleased processors we can’t support them until after release. If you have access to an Emerald Rapids CPU, please contact your Intel representative to get access to the PCM NDA package. If you work at Intel, contact us on our Intel addresses so we can point you to the internal PCM site.
