### ISSUE TITLE
Access to Intel(r) Performance Counter Monitor has denied (Performance Monitoring Unit is occupied by other application)

### ISSUE THREAD

**Issue by zhaowq32** [intel/pcm#608]
operating system: MacOS 12.7.1
CPU: i9-9980HK
Clang version:Apple clang version 13.1.6 (clang-1316.0.21.2.5)
![image](https://github.com/intel/pcm/assets/21306664/0b774db1-272f-41be-afcb-c9f7b6195007)

**Comment by opcm** [comment]
do any other PMU tools run in parallel? you can try to run pcm with the -r flag

**Comment by zhaowq32** [comment]
It's not working with -r flag.Maybe iStats Menus?

**Comment by rdementi** [comment]
try to stop the other app you suspect and re-run  "pcm -r"

**Comment by zhaowq32** [comment]
Still not working

**Comment by opcm** [comment]
are you running pcm as root?

**Comment by zhaowq32** [comment]
No,i will have a try with sudo.

**Comment by zhaowq32** [comment]
Not working

**Comment by rdementi** [comment]
please share a complete output of "sudo pcm -r"

**Comment by zhaowq32** [comment]
➜  bin git:(master) sudo ./pcm -r

 Intel(r) Performance Counter Monitor ($Format:%ci ID=%h$)



=====  Processor information  =====
Hybrid processor         : no
IBRS and IBPB supported  : yes
STIBP supported          : yes
Spec arch caps supported : yes
Max CPUID level          : 22
CPU model number         : 158
IOServiceOpen returned 0x10000003
Unable to build CPU topology

 Resetting PMU configuration
 Zeroed PMU registers
WARNING: Core 0 IA32_PERFEVTSEL0_ADDR is not zeroed 18446744073709551615
Access to Intel(r) Performance Counter Monitor has denied (Performance Monitoring Unit is occupied by other application). Try to stop the application that uses PMU.
Alternatively you can try running PCM with option -r to reset PMU.
Cleaning up
 Zeroed PMU registers
 Zeroed uncore PMU registers

**Comment by rdementi** [comment]
could you try the released version here (https://github.com/intel/pcm/releases/tag/202311 )? Recompile both the PCM MSR driver and PCM itself please

**Comment by opcm** [comment]
There is a different error "IOServiceOpen returned 0x10000003" above which might point to the issue: PCM MSR driver could not be loaded. Did you try the manual install procedure: https://github.com/intel/pcm/blob/master/doc/MAC_HOWTO.txt 
Could you share the output of kextstat ?

**Comment by zhaowq32** [comment]
Requires kext signing or turning off SIP.
```
2023-11-23 08:41:31.845 xcodebuild[7394:40866] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
2023-11-23 08:41:31.846 xcodebuild[7394:40866] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
Error Domain=KMErrorDomain Code=29 "Authenticating extension failed: Kext com.intel.driver.PcmMsr v1 in executable kext bundle com.intel.driver.PcmMsr at /private/var/db/KernelExtensionManagement/Staging/com.intel.driver.PcmMsr.H27GvM/PcmMsrDriver.kext:

Authenticating extension failed: Bad code signature" UserInfo={NSLocalizedDescription=Authenticating extension failed: Kext com.intel.driver.PcmMsr v1 in executable kext bundle com.intel.driver.PcmMsr at /private/var/db/KernelExtensionManagement/Staging/com.intel.driver.PcmMsr.H27GvM/PcmMsrDriver.kext:

Authenticating extension failed: Bad code signature}
```
