### ISSUE TITLE
CPU not supported by pcm-pcie

### ISSUE THREAD

**Issue by SuperWangKai** [intel/pcm#692]
My CPU is [i9-12900K](https://www.intel.com/content/www/us/en/products/sku/134599/intel-core-i912900k-processor-30m-cache-up-to-5-20-ghz/specifications.html). When using the tool pcm-pcie, the CPU is not supported:
https://github.com/intel/pcm/blob/59c8308cacadb24b230852147e1f140eb9c6d480/src/pcm-pcie.cpp#L241

**Comment by opcm** [comment]
this won't be supported: https://github.com/intel/pcm/blob/master/doc/FAQ.md#q12
