### ISSUE TITLE
Unsupported for  Intel(R) Xeon(R) Silver 4410Y

### ISSUE THREAD

**Issue by pudding-art** [intel/pcm#697]
>ppm
Processor Counter Monitor  (202201-1)
Linux arch_perfmon flag  : yes
Hybrid processor         : no
IBRS and IBPB supported  : yes
STIBP supported          : yes
Spec arch caps supported : yes
Error: unsupported processor. Only Intel(R) processors are supported (Atom(R) and microarchitecture codename Nehalem/Nehalem-EP, Atom(tm), Westmere/Clarkdale, Sandy Bridge, Westmere-EP, Sandy Bridge-EP/Jaketown, Nehalem-EX, Westmere-EX, unknown, Centerton, Baytrail, Ivy Bridge, Haswell, Broadwell, Ivy Bridge-EP/EN/EX/Ivytown, Haswell-EP/EN/EX, Cherrytrail, Avoton, Skylake U/Y, Broadwell-EP/EX, Skylake-SP, Cascade Lake-SP, Broadwell-DE, Knights Landing, Apollo Lake, Skylake, Denverton, Icelake-SP, Icelake, Snowridge, Tiger Lake, Kabylake/Whiskey Lake, Alder Lake, Kabylake, Comet Lake, Rocket Lake). CPU model number: 143 Brand: "Intel(R) Xeon(R) Silver 4410Y"
Access to Processor Counter Monitor has denied (no MSR or PCI CFG space access).

How to solve it?

**Comment by rdementi** [comment]
please use the latest version. 202201 is too old.
