### ISSUE TITLE
pcm-sensor-server generated grafana dashboard uses unsupported grafana plugins

### ISSUE THREAD

**Issue by vimalk78** [intel/pcm#730]
grafana dashboard returned by `pcm-sensor-server` contains elements which are deprecated by latest grafana.

Need to use`TimeSeries` instead of  `Graph` which is older way

![image](https://github.com/intel/pcm/assets/3284044/36f4deef-f917-4341-b2b4-d5500f0a96cd)

![image](https://github.com/intel/pcm/assets/3284044/b8993f8e-ef88-4730-9ec4-b06d42f96281)

**Comment by rdementi** [comment]
thanks for opening the issue. Let us know if you able to submit a pull request. If not we will address it asap

**Comment by ogbrugge** [comment]
If you edit the panel it will propose a conversion. Accept the conversion, look at the difference in the Grafana xml, then modify the Grafana generator to use the converted code. Should not be too hard if you know a little scripting.

**Comment by rdementi** [comment]
it turned out to be easier than I thought:
```
diff --git a/src/dashboard.cpp b/src/dashboard.cpp
index 97a827f..62c7d2e 100644
--- a/src/dashboard.cpp
+++ b/src/dashboard.cpp
@@ -325,7 +325,7 @@ public:
         "sort": 0,
         "value_type": "individual"
       },
-      "type": "graph",
+      "type": "timeseries",
       "xaxis": {
         "buckets": null,
         "mode": "time",
```

**Comment by vimalk78** [comment]
i also thought of the same changes, + perhaps change class name from `GraphPanel` to `TimeSeriesPanel` ?
I can submit a PR.

**Comment by rdementi** [comment]
> i also thought of the same changes, + perhaps change class name from `GraphPanel` to `TimeSeriesPanel` ? I can submit a PR.

that would be awesome

**Comment by vimalk78** [comment]
PR for fix: https://github.com/intel/pcm/pull/732
