### ISSUE TITLE
The build failed because of a runtime libraries incompatibility

### ISSUE THREAD

**Issue by artiomn** [intel/pcm#774]
@rdementi , why do you added `/MT$<$<CONFIG:Debug>:d>` in the CMakeLists?

It breaks builds with another types of runtime and doesn't work in the most cases, due to library incompatibility.
If I comment out the two lines with `target_compile_options`, the library and my project are built successfully.

Could you remove this options?

```
    target_compile_options(PCM_STATIC PRIVATE "/MT$<$<CONFIG:Debug>:d>")

    # Graphical perfmon front-end: pcm-lib, pcm-service
    # Files: COMMON_FILES() + pcm-lib.cpp winpmem\winpmem.cpp dllmain.cpp
    file(GLOB PCM_LIB_SOURCES winpmem/winpmem.cpp dllmain.cpp pcm-lib.cpp )
    add_library(pcm-lib SHARED ${COMMON_SOURCES} ${PCM_LIB_SOURCES})
    target_compile_definitions(pcm-lib PRIVATE _WINDOWS _USRDLL PCM_EXPORTS _WINDLL _UNICODE UNICODE)

    target_compile_options(pcm-lib PRIVATE "/MT$<$<CONFIG:Debug>:d>")
```

P.S.: It's incorrect to use compiler options to specify runtime: CMake has built-in variables and properties for it, but libraries should not to use this.

**Comment by rdementi** [comment]
Thanks for the suggestion. The change was introduced to reduce the risks of DLL hijacking.

Would you be able to submit a pull request with a CMakeLists.txt change to specify the runtime using the built-in variables and properties?

**Comment by rdementi** [comment]
thanks for the recipe. We will evaluate it. As a work-around we can offer a new -DNO_STATIC_MSVC_RUNTIME_LIBRARY=1 option which you can use with cmake when compiling pcm.

**Comment by artiomn** [comment]
Thank you. It's better than nothing. But if you have a real reason to set the runtime library (like formal SDL requirements), perhaps in the future it would be better to add an option where the user can set an arbitrary runtime?
