### ISSUE TITLE
Cannot build pcm on server

### ISSUE THREAD

**Issue by karynhuang55** [intel/pcm#868]
Hello developers, I tried to compile pcm on my server, but it failed. Here is the error output:
[root@ocp-node1 build]# cmake --build .
[  1%] Building CXX object src/CMakeFiles/PCM_STATIC.dir/cpucounters.cpp.o
In file included from /usr/include/c++/12/mutex:43,
                 from /mnt/pcm/src/resctrl.h:17,
                 from /mnt/pcm/src/cpucounters.h:70,
                 from /mnt/pcm/src/cpucounters.cpp:23:
/usr/include/c++/12/bits/std_mutex.h: In member function ‘void std::__condvar::wait_until(std::mutex&, clockid_t, timespec&)’:
/usr/include/c++/12/bits/std_mutex.h:169:7: error: ‘pthread_cond_clockwait’ was not declared in this scope; did you mean ‘pthread_cond_wait’?
  169 |       pthread_cond_clockwait(&_M_cond, __m.native_handle(), __clock,
      |       ^~~~~~~~~~~~~~~~~~~~~~
      |       pthread_cond_wait
/usr/include/c++/12/mutex: In member function ‘bool std::timed_mutex::_M_clocklock(clockid_t, const __gthread_time_t&)’:
/usr/include/c++/12/mutex:272:17: error: ‘pthread_mutex_clocklock’ was not declared in this scope; did you mean ‘pthread_mutex_unlock’?
  272 |       { return !pthread_mutex_clocklock(&_M_mutex, clockid, &__ts); }
      |                 ^~~~~~~~~~~~~~~~~~~~~~~
      |                 pthread_mutex_unlock
/usr/include/c++/12/mutex: In member function ‘bool std::recursive_timed_mutex::_M_clocklock(clockid_t, const __gthread_time_t&)’:
/usr/include/c++/12/mutex:338:17: error: ‘pthread_mutex_clocklock’ was not declared in this scope; did you mean ‘pthread_mutex_unlock’?
  338 |       { return !pthread_mutex_clocklock(&_M_mutex, clockid, &__ts); }
      |                 ^~~~~~~~~~~~~~~~~~~~~~~
      |                 pthread_mutex_unlock
gmake[2]: *** [src/CMakeFiles/PCM_STATIC.dir/build.make:90: src/CMakeFiles/PCM_STATIC.dir/cpucounters.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:182: src/CMakeFiles/PCM_STATIC.dir/all] Error 2
gmake: *** [Makefile:156: all] Error 2

**Comment by rdementi** [comment]
Hi,

could you please provide more details about your operating system and version?
Please also build from scratch in a new directory and provide the output from the first cmake command "cmake .."

**Comment by rdementi** [comment]
this issue seems to be similar: https://github.com/jive-vlbi/etransfer?tab=readme-ov-file#gcc12--debian12-bookworm-build-problems

**Comment by karynhuang55** [comment]
> this issue seems to be similar: https://github.com/jive-vlbi/etransfer?tab=readme-ov-file#gcc12--debian12-bookworm-build-problems

It works! Thanks for your help.
