### ISSUE TITLE
IPv6 Support

### ISSUE THREAD

**Issue by arun2arunraj** [intel/pcm#887]
Our environment is fully IPv6 based. Do we have support for the IPv6 environment to scrape ?

**Comment by opcm** [comment]
I am not sure. We did not test with IPv6. If you see any issue please report.

**Comment by arun2arunraj** [comment]
I see already see issues. It is not at at all listening in IPv6 interface. That's why raised it here. 

Listening port is in the IPv4

`netstat -tulpen | grep 9738
tcp        0      0 0.0.0.0:9738            0.0.0.0:*               LISTEN      0          1947042561 2554081/pcm-sensor- `


IPv6 curl response :

`curl -kg http://[fab0:fbc:10:ed:c07:2002:1:0]:9738/metrics
curl: (7) Failed to connect to fab0:fbc:10:ed:c07:2002:1:0 port 9738: Connection refused`

IPv4 curl response :

`curl -kg http://localhost:9738/metrics | more
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Measurement_Interval_in_us 5871520362957
Number_of_sockets 2
# Core Counters Socket 0
OS_ID{socket="0",core="0",thread="0"} 0
Instructions_Retired_Any{socket="0",core="0",thread="0",source="core"} 9669122068
Clock_Unhalted_Thread{socket="0",core="0",thread="0",source="core"} 8874702726
Clock_Unhalted_Ref{socket="0",core="0",thread="0",source="core"} 20102499648
L3_Cache_Misses{socket="0",core="0",thread="0",source="core"} 4122715
L3_Cache_Hits{socket="0",core="0",thread="0",source="core"} 7684222
L2_Cache_Misses{socket="0",core="0",thread="0",source="core"} 14702458
L2_Cache_Hits{socket="0",core="0",thread="0",source="core"} 65103198
L3_Cache_Occupancy{socket="0",core="0",thread="0",source="core"} 9856
Invariant_TSC{socket="0",core="0",thread="0",source="core"} 12887911428044027
SMI_Count{socket="0",core="0",thread="0",source="core"} 6702
Thermal_Headroom{socket="0",core="0",thread="0",source="core"} 63
CStateResidency{socket="0",core="0",thread="0",source="core",index="0"} 0.000
RawCStateResidency{socket="0",core="0",thread="0",source="core",index="0"} 20102499648
CStateResidency{socket="0",core="0",thread="0",source="core",index="1"} 1.000
RawCStateResidency{socket="0",core="0",thread="0",source="core",index="1"} 0
CStateResidency{socket="0",core="0",thread="0",source="core",index="2"} 0.000
RawCStateResidency{socket="0",core="0",thread="0",source="core",index="2"} 0
CStateResidency{socket="0",core="0",thread="0",source="core",index="3"} 0.000
RawCStateResidency{socket="0",core="0",thread="0",source="core",index="3"} 0
CStateResidency{socket="0",core="0",thread="0",source="core",index="4"} 0.000
RawCStateResidency{socket="0",core="0",thread="0",source="core",index="4"} 0
CStateResidency{socket="0",core="0",thread="0",source="core",index="5"} 0.000
RawCStateResidency{socket="0",core="0",thread="0",source="core",index="5"} 0
CStateResidency{socket="0",core="0",thread="0",source="core",index="6"} 0.000
RawCStateResidency{socket="0",core="0",thread="0",source="core",index="6"} 38141065569
CStateResidency{socket="0",core="0",thread="0",source="core",index="7"} 0.000
RawCStateResidency{socket="0",core="0",thread="0",source="core",index="7"} 0
CStateResidency{socket="0",core="0",thread="0",source="core",index="8"} 0.000
RawCStateResidency{socket="0",core="0",thread="0",source="core",index="8"} 0
CStateResidency{socket="0",core="0",thread="0",source="core",index="9"} 0.000
RawCStateResidency{socket="0",core="0",thread="0",source="core",index="9"} 0
CStateResidency{socket="0",core="0",thread="0",source="core",index="10"} 0.000
RawCStateResidency{socket="0",core="0",thread="0",source="core",index="10"} 0
Local_Memory_Bandwidth{socket="0",core="0",thread="0",source="core"} 69595
Remote_Memory_Bandwidth{socket="0",core="0",thread="0",source="core"} 26745
OS_ID{socket="0",core="0",thread="1"} 64
Instructions_Retired_Any{socket="0",core="0",thread="1",source="core"} 8247252179`


The following is the pcm-sensor-server start logs

> pcm-sensor-server -d

=====  Processor information  =====
[root@d703ssrms10701 ~]# Linux arch_perfmon flag  : yes
Hybrid processor         : no
IBRS and IBPB supported  : yes
STIBP supported          : yes
Spec arch caps supported : yes
Max CPUID level          : 27
CPU model number         : 106
Number of physical cores: 64
Number of logical cores: 128
Number of online logical cores: 128
Threads (logical cores) per physical core: 2
Num sockets: 2
Physical cores per socket: 32
Last level cache slices per socket: 32
Core PMU (perfmon) version: 5
Number of core PMU generic (programmable) counters: 8
Width of generic (programmable) counters: 48 bits
Number of core PMU fixed counters: 4
Width of fixed counters: 48 bits
Nominal core frequency: 2200000000 Hz
IBRS enabled in the kernel   : yes
STIBP enabled in the kernel  : no
The processor is not susceptible to Rogue Data Cache Load: yes
The processor supports enhanced IBRS                     : yes
Package thermal spec power: 185 Watt; Package minimum power: 84 Watt; Package maximum power: 652 Watt;

INFO: Linux perf interface to program uncore PMUs is present
Socket 0: 4 memory controllers detected with total number of 8 channels. 3 UPI ports detected. 4 M2M (mesh to memory) blocks detected. 0 Home Agents detected. 3 M3UPI blocks detected.
Socket 1: 4 memory controllers detected with total number of 8 channels. 3 UPI ports detected. 4 M2M (mesh to memory) blocks detected. 0 Home Agents detected. 3 M3UPI blocks detected.
Initializing RMIDs

 Disabling NMI watchdog since it consumes one hw-PMU counter. To keep NMU watchdog set environment variable PCM_KEEP_NMI_WATCHDOG=1 (this reduces the core metrics set)
 Closed perf event handles
Trying to use Linux perf events...
Successfully programmed on-core PMU using Linux perf
Socket 0
Max UPI link 0 speed: 25.1 GBytes/second (11.2 GT/second)
Max UPI link 1 speed: 25.1 GBytes/second (11.2 GT/second)
Max UPI link 2 speed: 25.1 GBytes/second (11.2 GT/second)
Socket 1
Max UPI link 0 speed: 25.1 GBytes/second (11.2 GT/second)
Max UPI link 1 speed: 25.1 GBytes/second (11.2 GT/second)
Max UPI link 2 speed: 25.1 GBytes/second (11.2 GT/second)
Starting plain HTTP server on http://localhost:9738/

**Comment by ogbrugge** [comment]
If i find some time this week i will try to get this done before i go on vacation next week but i do not have a way to test this easily, no network where i can easily play with IPv6. I may ask for your help with some commits for you to test

**Comment by ogbrugge** [comment]
Can you try this patch?

diff --git a/src/pcm-sensor-server.cpp b/src/pcm-sensor-server.cpp
index b86e273e..8e877359 100644
--- a/src/pcm-sensor-server.cpp
+++ b/src/pcm-sensor-server.cpp
@@ -1320,26 +1320,26 @@ private:
         if ( port_ == 0 )
             throw std::runtime_error( "Server Constructor: No port specified." );

-        int sockfd = ::socket( AF_INET, SOCK_STREAM, 0 );
+        int sockfd = ::socket( AF_INET6, SOCK_STREAM, 0 );
         if ( -1 == sockfd )
             throw std::runtime_error( "Server Constructor: Can´t create socket" );

         int retval = 0;

-        struct sockaddr_in serv;
-        serv.sin_family = AF_INET;
-        serv.sin_port = htons( port_ );
+        struct sockaddr_in6 serv;
+        serv.sin6_family = AF_INET6;
+        serv.sin6_port = htons( port_ );
         if ( listenIP_.empty() )
-            serv.sin_addr.s_addr = INADDR_ANY;
+            serv.sin6_addr = in6addr_any;
         else {
-            if ( 1 != ::inet_pton( AF_INET, listenIP_.c_str(), &(serv.sin_addr) ) )
+            if ( 1 != ::inet_pton( AF_INET6, listenIP_.c_str(), &(serv.sin6_addr) ) )
             {
                 DBG( 3, "close clientsocketFD" );
                 ::close(sockfd);
                 throw std::runtime_error( "Server Constructor: Cannot convert IP string" );
             }
         }
-        socklen_t len = sizeof( struct sockaddr_in );
+        socklen_t len = sizeof( struct sockaddr_in6 );
         retval = ::bind( sockfd, reinterpret_cast<struct sockaddr*>(&serv), len );
         if ( 0 != retval ) {
             DBG( 3, "close clientsocketFD" );

After this patch i can still run the daemon as ipv4 so no regressions but i have not been able to test it with ipv6 yet.

**Comment by arun2arunraj** [comment]
Sure I can test it. Which docker image has this patch ?

**Comment by rdementi** [comment]
Right now there is no docker image with this patch. We are going to take this change into the master branch and then the default pcm container will have it. I will let you know asap when it will be there.

**Comment by rdementi** [comment]
the container is ready: https://github.com/intel/pcm/pkgs/container/pcm

**Comment by ogbrugge-work** [comment]
Thank you!

**Comment by arun2arunraj** [comment]
This has been sorted. All looks good. Now the images support IPv6.

**Comment by ogbrugge-work** [comment]
Good to hear! Thanks for testing!
