### ISSUE TITLE
Is Arrow Lake currently supported?

### ISSUE THREAD

**Issue by 0jaehunny0** [intel/pcm#894]
I have two questions:
1. Is Arrow Lake currently supported by PCM?
2. If it is not supported yet, when is support expected?

I am an Arrow Lake 285k user.
I followed your manual to build PCM on Windows, but it doesn't work and shows the following 577 error:
```
Starting MSR service failed with error 577
Trying to load winring0.dll/winring0.sys driver...
Failed to load winring0.dll/winring0.sys driver.
Access to Intel(r) Performance Counter Monitor has denied (no MSR or PCI CFG space access).
```

I couldn’t find any mention of Arrow Lake in your release notes.
Is the error my bad, or is it because PCM doesn’t support Arrow Lake yet?

**Comment by opcm** [comment]
Hi, Arrow Lake is supported. The error above could be due to an antivirus software blocking the Winring0 driver.

**Comment by soneryaldiz** [comment]
Is PCM supported for Arrow Lake running Ubuntu?

**Comment by rdementi** [comment]
the upstream PCM version has support of Arrow Lake on Ubuntu (at least the main pcm utility should run). In general not all pcm utilities are supported on client CPUs (see the FAQ).
